function mdb_createDatabaseAIS(meas, conn, collection_name)

nmeas = numel(meas.times);
for i = 1:nmeas
    newdata = struct(...
        "time", meas.times(i),...
        "datenum", datenum(meas.times(i)),...
        "type", "AIS",...
        "lat", meas.coords(i, 2), "lon", meas.coords(i,1),...
        "mmsi", meas.mmsi{i});
    n = insert(conn, collection_name, newdata);
end

end
